# Generated by Django 4.2 on 2023-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'ok'), (2, 'fine'), (3, 'good'), (4, 'amasing'), (5, 'incredible')], null=True),
        ),
    ]
